namespace Networking
{
    public enum RequestType
    {
        LOGIN, LOGOUT, SIGNUP, GET_COMPETITIONS, REGISTER_PARTICIPANT, GET_PARTICIPANTS, GET_NR_PARTICIPANTS, GET_REGISTRATIONS, GET_PARTICIPANTS_FOR_COMPETITION
    }
}